# Generated by Django 3.1.5 on 2021-01-30 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='phone',
            field=models.PositiveIntegerField(default='01010101010', unique=True, verbose_name='phone number'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='profile_image',
            field=models.ImageField(default=None, height_field=300, upload_to='img/', verbose_name='profile image', width_field=300),
        ),
    ]
