# Generated by Django 3.1.5 on 2021-02-01 00:47

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20210131_1929'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='phone',
            field=models.CharField(blank=True, max_length=17, validators=[django.core.validators.RegexValidator(message="Phone number must be like: '+999999999'. Up to 15 digits.", regex='^\\+?1?\\d{9,15}$')], verbose_name='phone number'),
        ),
    ]
